name: Release
on:
  workflow_dispatch:
    inputs:
      arbitrary_text_string:
        description: Pass this to CircleCI
        required: true
        type: string

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}