attach_workspace_at: &attach_workspace_at
  attach_workspace:
    at: .


parameters:
  destination:
    type: string
    default: none
  workflow_name:
    type: string
    default: none

version: 2.1
jobs:
  some-custom-command:
    docker:
      - image: bash:latest
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace_at
      - mystep:
          name: Send to << pipeline.parameters.destination >>
          command: |
            echo "I did something"

workflows:
  version: 2

  remotely-triggered:
    when:
      and:
        - equal: [ 'arbitrary_value', << pipeline.parameters.workflow_name >> ]
    jobs:
      - some-custom-command:
          context: special-context
