attach_workspace_at: &attach_workspace_at
  attach_workspace:
    at: .

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

version: 2.1
jobs:
  some-custom-command:
    docker:
      - image: bash:latest
    steps:
      - setup_remote_docker
      - checkout
      - <<: *attach_workspace_at
      - run:
          name: GHA_Actor
          command: |
            echo << pipeline.parameters.GHA_Actor >>
      - run:
          name: GHA_Action
          command: |
            echo << pipeline.parameters.GHA_Action >>
      - run:
          name: GHA_Event
          command: |
            echo << pipeline.parameters.GHA_Event >>
      - run:
          name: GHA_Meta
          command: |
            << pipeline.parameters.GHA_Meta >>

workflows:
  version: 2

  remotely-triggered:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - some-custom-command
