name: Release
on:
  workflow_dispatch:
    inputs:
      circleci_command:
        description: Run this command in CircleCI
        required: true
        type: string

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Meta: ${{ github.event.inputs.circleci_command }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
