name: Workflow Deployment

on:
  workflow_call:
    inputs:
      environment_name:
        description: Deployment environment
        required: true
        type: string
      git_ref:
        description: Git ref
        required: true
        type: string
    secrets:
      auth_token:
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ${{ inputs.git_ref }} to ${{ inputs.environment_name }} with CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Meta: echo "Deploying ${{ inputs.git_ref }} to ${{ inputs.environment_name }}..."
        env:
          CCI_TOKEN: ${{ inputs.auth_token }}
