name: Workflow Deployment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: Deployment environment
        required: true
        type: environment

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ${{ github.event.inputs.environment_name }} with CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Meta: echo "Deploying to ${{ github.event.inputs.environment_name }}..."
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
